### ISSUE TITLE
Not working with Atom 0.207

### ISSUE THREAD

**Issue by rmg** [AbeEstrada/atom-remember-window#2]
[Enter steps to reproduce below:]
1. Open Atom 0.200.0 or later
2. see failure to load

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [remember-window](https://github.com/AbeEstrada/atom-remember-window) package, v0.3.0
### Stack Trace

Failed to activate the remember-window package

```
At undefined is not a function

TypeError: undefined is not a function
    at setWindowDimensions (/Users/ryan/.atom/packages/remember-window/lib/remember-window.coffee:86:7)
    at Object.module.exports.activate (/Users/ryan/.atom/packages/remember-window/lib/remember-window.coffee:22:7)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "projectHome": "/Users/ryan/work",
    "destroyEmptyPanes": false
  },
  "remember-window": {
    "x": 51,
    "y": -1057,
    "width": 1869,
    "height": 1057,
    "treeWidth": 200
  }
}
```
### Installed Packages

``` coffee
# User
language-docker, v1.1.3
remember-window, v0.3.0

# Dev
language-make, v0.9.0
```

**Comment by AbeEstrada** [comment]
This package is not required anymore to make Atom remember your window position, this feature was added a lot versions ago and you can uninstall it and Atom will remember your window position by default. I unpublished this package 10 months ago. I'm not going to update it because now it's not necessary.

**Comment by rmg** [comment]
@AbeEstrada woops! Sorry for the github noise, and thanks for making the package in the first place :-)
